# Generated by Django 5.2.10 on 2026-02-04 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("assets", "0012_remove_posicaocomponente_motor_and_more"),
        ("core", "0001_initial"),
        ("inventory", "0003_alter_estoqueitem_minimo_seguranca_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PosicaoComponente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                (
                    "serial_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Nº de Série",
                    ),
                ),
                (
                    "data_instalacao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Última Troca"
                    ),
                ),
                ("hora_motor_instalacao", models.IntegerField(default=0)),
                ("arranques_motor_instalacao", models.IntegerField(default=0)),
                ("data_ultima_coleta", models.DateField(blank=True, null=True)),
                ("horas_na_coleta", models.IntegerField(blank=True, null=True)),
                ("data_ultima_analise", models.DateField(blank=True, null=True)),
                (
                    "resultado_ultima_coleta",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("ultima_medicao_vibracao", models.DateField(blank=True, null=True)),
                ("ultimo_engraxamento", models.DateField(blank=True, null=True)),
                (
                    "motor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="componentes",
                        to="assets.motor",
                    ),
                ),
                (
                    "peca_instalada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.catalogopeca",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "verbose_name": "Componente Geral",
                "verbose_name_plural": "1. Lista Geral",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Periferico",
            fields=[],
            options={
                "verbose_name": "Periférico",
                "verbose_name_plural": "3. Periféricos",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("components.posicaocomponente",),
        ),
        migrations.CreateModel(
            name="SistemaOleo",
            fields=[],
            options={
                "verbose_name": "Item de Óleo",
                "verbose_name_plural": "2. Óleo",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("components.posicaocomponente",),
        ),
    ]
