# Generated by Django 5.2.10 on 2026-02-04 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0013_delete_posicaocomponente"),
        ("components", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GrupoComponente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        default=0, help_text="Ordem de exibição na tela"
                    ),
                ),
                (
                    "motor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grupos",
                        to="assets.motor",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "verbose_name": "Grupo de Componentes",
                "verbose_name_plural": "Grupos de Componentes",
                "ordering": ["ordem", "nome"],
                "unique_together": {("motor", "nome")},
            },
        ),
        migrations.DeleteModel(
            name="Periferico",
        ),
        migrations.DeleteModel(
            name="SistemaOleo",
        ),
        migrations.AlterModelOptions(
            name="posicaocomponente",
            options={
                "ordering": ["grupo__ordem", "grupo__nome", "nome"],
                "verbose_name": "Componente",
                "verbose_name_plural": "Gestão de Componentes",
            },
        ),
        migrations.AddField(
            model_name="posicaocomponente",
            name="grupo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="itens",
                to="components.grupocomponente",
                verbose_name="Categoria / Grupo",
            ),
        ),
    ]
