# Generated by Django 5.2.10 on 2026-02-04 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "components",
            "0002_grupocomponente_delete_periferico_delete_sistemaoleo_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuFiltros",
            fields=[],
            options={
                "verbose_name": "Item de Filtro",
                "verbose_name_plural": "2. Filtros (Ar/Gás)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("components.posicaocomponente",),
        ),
        migrations.CreateModel(
            name="MenuIgnicao",
            fields=[],
            options={
                "verbose_name": "Item de Ignição",
                "verbose_name_plural": "4. Ignição / Elétrica",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("components.posicaocomponente",),
        ),
        migrations.CreateModel(
            name="MenuOleo",
            fields=[],
            options={
                "verbose_name": "Item de Óleo",
                "verbose_name_plural": "1. Sistema de Óleo",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("components.posicaocomponente",),
        ),
        migrations.CreateModel(
            name="MenuOutros",
            fields=[],
            options={
                "verbose_name": "Outro Item",
                "verbose_name_plural": "5. Outros / Personalizados",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("components.posicaocomponente",),
        ),
        migrations.CreateModel(
            name="MenuPerifericos",
            fields=[],
            options={
                "verbose_name": "Periférico",
                "verbose_name_plural": "3. Periféricos",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("components.posicaocomponente",),
        ),
        migrations.AlterModelOptions(
            name="grupocomponente",
            options={
                "ordering": ["ordem", "nome"],
                "verbose_name": "Gerenciar Categoria",
                "verbose_name_plural": "Gerenciar Categorias",
            },
        ),
        migrations.AlterModelOptions(
            name="posicaocomponente",
            options={
                "ordering": ["grupo__ordem", "nome"],
                "verbose_name": "Componente Geral",
                "verbose_name_plural": "Todos os Componentes",
            },
        ),
        migrations.AddField(
            model_name="grupocomponente",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="grupocomponente",
            name="ordem",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="posicaocomponente",
            name="grupo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="itens",
                to="components.grupocomponente",
                verbose_name="Categoria",
            ),
        ),
    ]
