# Generated by Django 5.2.10 on 2026-02-04 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("components", "0003_menufiltros_menuignicao_menuoleo_menuoutros_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuCabecotes",
            fields=[],
            options={
                "verbose_name": "Item de Cabeçote",
                "verbose_name_plural": "6. Cabeçotes",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("components.posicaocomponente",),
        ),
        migrations.CreateModel(
            name="MenuCilindros",
            fields=[],
            options={
                "verbose_name": "Item de Cilindro",
                "verbose_name_plural": "5. Cilindros (Power Pack)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("components.posicaocomponente",),
        ),
        migrations.AlterModelOptions(
            name="menuoutros",
            options={
                "verbose_name": "Outro Item",
                "verbose_name_plural": "7. Outros / Personalizados",
            },
        ),
        migrations.AlterModelOptions(
            name="posicaocomponente",
            options={
                "ordering": ["grupo__ordem", "nome"],
                "verbose_name": "Componente",
                "verbose_name_plural": "Todos os Componentes",
            },
        ),
        migrations.AlterField(
            model_name="posicaocomponente",
            name="grupo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="itens",
                to="components.grupocomponente",
            ),
        ),
    ]
