# Generated by Django 5.2.10 on 2026-02-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "components",
            "0004_menucabecotes_menucilindros_alter_menuoutros_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="posicaocomponente",
            options={
                "ordering": ["grupo__ordem", "nome_base", "numero"],
                "verbose_name": "Componente",
                "verbose_name_plural": "Todos os Componentes",
            },
        ),
        migrations.AddField(
            model_name="posicaocomponente",
            name="nome_base",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Tipo do Item"
            ),
        ),
        migrations.AddField(
            model_name="posicaocomponente",
            name="numero",
            field=models.PositiveIntegerField(default=0, verbose_name="Sequência"),
        ),
    ]
