# Generated by Django 5.2.10 on 2026-02-05 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("components", "0005_alter_posicaocomponente_options_and_more"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanoPreventiva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tarefa", models.CharField(max_length=100)),
                (
                    "intervalo_horas",
                    models.PositiveIntegerField(
                        help_text="Executar a cada X horas de operação"
                    ),
                ),
                (
                    "intervalo_meses",
                    models.PositiveIntegerField(
                        blank=True, help_text="Opcional: Validade temporal", null=True
                    ),
                ),
                (
                    "posicao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planos_preventiva",
                        to="components.posicaocomponente",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
