# Generated by Django 5.2.10 on 2026-02-05 01:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("components", "0006_planopreventiva"),
    ]

    operations = [
        migrations.AddField(
            model_name="planopreventiva",
            name="tipo_servico",
            field=models.CharField(
                choices=[
                    ("SUBSTITUICAO", "Substituição (Troca de Peça)"),
                    ("INSTALACAO", "Instalação (Nova Peça)"),
                    ("REGULAGEM", "Regulagem"),
                    ("LUBRIFICACAO", "Lubrificação"),
                    ("CALIBRACAO", "Calibração"),
                    ("INSPECAO", "Inspeção / Rotina"),
                    ("LIMPEZA", "Limpeza"),
                ],
                default="INSPECAO",
                help_text="Quando este tipo de serviço for lançado no Livro de Ocorrências, este plano será reiniciado.",
                max_length=50,
                verbose_name="Gatilho de Reset",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="planopreventiva",
            name="ultima_execucao_horas",
            field=models.IntegerField(
                default=0, verbose_name="Horímetro na Última Execução"
            ),
        ),
        migrations.AlterField(
            model_name="planopreventiva",
            name="intervalo_horas",
            field=models.PositiveIntegerField(help_text="Intervalo (em horas)"),
        ),
        migrations.AlterField(
            model_name="planopreventiva",
            name="tarefa",
            field=models.CharField(
                help_text="Ex: Trocar Óleo",
                max_length=100,
                verbose_name="Nome da Tarefa",
            ),
        ),
    ]
