# Generated by Django 5.2.10 on 2026-02-05 03:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("components", "0007_planopreventiva_tipo_servico_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="planopreventiva",
            name="intervalo_horas",
        ),
        migrations.RemoveField(
            model_name="planopreventiva",
            name="intervalo_meses",
        ),
        migrations.RemoveField(
            model_name="planopreventiva",
            name="ultima_execucao_horas",
        ),
        migrations.AddField(
            model_name="planopreventiva",
            name="intervalo_valor",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Ex: 500 (Horas), 6 (Meses), 1000 (Arranques)",
                verbose_name="Intervalo",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="planopreventiva",
            name="ultima_execucao_data",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data Última Execução"
            ),
        ),
        migrations.AddField(
            model_name="planopreventiva",
            name="ultima_execucao_valor",
            field=models.IntegerField(
                default=0,
                help_text="Armazena o horímetro ou nº de arranques da última troca",
                verbose_name="Último Contador (Horas/Arranques)",
            ),
        ),
        migrations.AddField(
            model_name="planopreventiva",
            name="unidade",
            field=models.CharField(
                choices=[
                    ("HORAS", "Horas de Operação"),
                    ("ARRANQUES", "Arranques / Partidas"),
                    ("DIAS", "Dias Corridos"),
                    ("MESES", "Meses"),
                ],
                default="HORAS",
                max_length=20,
                verbose_name="Controlar por",
            ),
        ),
        migrations.AlterField(
            model_name="planopreventiva",
            name="tarefa",
            field=models.CharField(max_length=100, verbose_name="Nome da Tarefa"),
        ),
        migrations.AlterField(
            model_name="planopreventiva",
            name="tipo_servico",
            field=models.CharField(
                choices=[
                    ("SUBSTITUICAO", "Substituição (Troca de Peça)"),
                    ("INSTALACAO", "Instalação (Nova Peça)"),
                    ("REGULAGEM", "Regulagem"),
                    ("LUBRIFICACAO", "Lubrificação"),
                    ("CALIBRACAO", "Calibração"),
                    ("INSPECAO", "Inspeção / Rotina"),
                    ("LIMPEZA", "Limpeza"),
                ],
                help_text="Qual serviço no Livro de Ocorrências zera este plano?",
                max_length=50,
                verbose_name="Gatilho de Reset",
            ),
        ),
    ]
