# Generated by Django 5.2.10 on 2026-02-23 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0015_equipamento"),
        ("components", "0008_remove_planopreventiva_intervalo_horas_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="grupocomponente",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="grupocomponente",
            name="equipamento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grupos",
                to="assets.equipamento",
            ),
        ),
        migrations.AddField(
            model_name="posicaocomponente",
            name="equipamento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="componentes",
                to="assets.equipamento",
            ),
        ),
        migrations.AlterField(
            model_name="grupocomponente",
            name="motor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grupos",
                to="assets.motor",
            ),
        ),
        migrations.AlterField(
            model_name="posicaocomponente",
            name="motor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="componentes",
                to="assets.motor",
            ),
        ),
    ]
