# Generated by Django 5.2.10 on 2026-02-02 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaPeca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria de Peça",
                "verbose_name_plural": "Categorias de Peças",
            },
        ),
        migrations.CreateModel(
            name="CatalogoPeca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                (
                    "codigo_fabricante",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "requer_serial_number",
                    models.BooleanField(
                        default=False,
                        help_text="Se marcado, exige digitar o Nº de Série ao instalar (ex: Baterias, Turbos).",
                    ),
                ),
                (
                    "quantidade_por_jogo",
                    models.IntegerField(
                        default=1,
                        help_text="Ex: Anéis de segmento usam 3 por cilindro. Velas usam 1.",
                    ),
                ),
                (
                    "vida_util_horas",
                    models.IntegerField(
                        blank=True,
                        help_text="Limite de horas de operação (Ex: 2000h para Velas)",
                        null=True,
                    ),
                ),
                (
                    "vida_util_arranques",
                    models.IntegerField(
                        blank=True,
                        help_text="Limite de partidas (Ex: 1000 arranques para Baterias)",
                        null=True,
                    ),
                ),
                (
                    "vida_util_meses",
                    models.IntegerField(
                        blank=True,
                        help_text="Validade temporal (Ex: 6 meses para Óleo, mesmo parado)",
                        null=True,
                    ),
                ),
                ("alerta_amarelo_pct", models.IntegerField(default=90)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.categoriapeca",
                    ),
                ),
            ],
            options={
                "verbose_name": "Catálogo de Peça (Mestre)",
                "verbose_name_plural": "Catálogo de Peças (Mestre)",
                "unique_together": {("tenant", "codigo_fabricante")},
            },
        ),
        migrations.CreateModel(
            name="LocalEstoque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Ex: Armário A, Filial SP, Container 2",
                        max_length=100,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "verbose_name": "Local de Estoque",
                "verbose_name_plural": "Locais de Estoque",
            },
        ),
        migrations.CreateModel(
            name="EstoqueItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "minimo_seguranca",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "catalogo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estoques",
                        to="inventory.catalogopeca",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
                (
                    "local",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.localestoque",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item em Estoque",
                "verbose_name_plural": "Itens em Estoque",
                "unique_together": {("tenant", "catalogo", "local")},
            },
        ),
    ]
