# Generated by Django 5.2.10 on 2026-02-03 03:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0002_remove_motor_marca_marcamotor_modelomotor_and_more"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogopeca",
            name="aplicacao_universal",
            field=models.BooleanField(
                default=False,
                help_text="Marque se esta peça serve para qualquer aplicação (ex: Óleo, Ferramentas). Se marcado, a lista de modelos será ignorada.",
                verbose_name="Uso Universal / Genérico",
            ),
        ),
        migrations.AddField(
            model_name="catalogopeca",
            name="modelos_compativeis",
            field=models.ManyToManyField(
                blank=True,
                help_text="Se não for universal, selecione quais modelos de motor podem usar esta peça.",
                related_name="pecas_compativeis",
                to="assets.modelomotor",
                verbose_name="Modelos Compatíveis",
            ),
        ),
    ]
