# Generated by Django 5.2.10 on 2026-02-03 04:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_catalogopeca_aplicacao_universal_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estoqueitem",
            name="minimo_seguranca",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="estoqueitem",
            name="quantidade",
            field=models.IntegerField(
                default=0, help_text="Quantidade física (Inteiro)"
            ),
        ),
    ]
