# Generated by Django 5.2.10 on 2026-02-04 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("inventory", "0003_alter_estoqueitem_minimo_seguranca_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovimentoEstoque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ENTRADA", "Entrada (Compra/Retorno)"),
                            ("SAIDA", "Saída (Uso/Perda)"),
                            ("AJUSTE", "Ajuste de Inventário"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantidade", models.IntegerField()),
                ("data_movimento", models.DateTimeField(auto_now_add=True)),
                (
                    "origem",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Manutenção #123",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimentos",
                        to="inventory.estoqueitem",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimento de Estoque",
                "verbose_name_plural": "Histórico de Movimentações",
                "ordering": ["-data_movimento"],
            },
        ),
    ]
