# Generated by Django 5.2.10 on 2026-02-04 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("inventory", "0004_movimentoestoque"),
    ]

    operations = [
        migrations.CreateModel(
            name="SerialPeca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(max_length=100, verbose_name="Nº de Série"),
                ),
                ("data_entrada", models.DateField(auto_now_add=True)),
                (
                    "item_estoque",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seriais",
                        to="inventory.estoqueitem",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "verbose_name": "Serial Individual",
                "verbose_name_plural": "Seriais em Estoque",
                "unique_together": {("item_estoque", "serial_number")},
            },
        ),
    ]
