# Generated by Django 5.2.10 on 2026-02-07 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("inventory", "0005_serialpeca"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalogopeca",
            name="codigo_fabricante",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Cód. da Peça (Part Number)",
            ),
        ),
        migrations.CreateModel(
            name="Fabricante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("site", models.URLField(blank=True, null=True)),
                (
                    "principal",
                    models.BooleanField(
                        default=False,
                        help_text="Se marcado, aparecerá automaticamente selecionado ao criar uma nova peça.",
                        verbose_name="Fabricante Principal?",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "verbose_name": "Fabricante",
                "verbose_name_plural": "Fabricantes",
                "ordering": ["nome"],
            },
        ),
        migrations.AddField(
            model_name="catalogopeca",
            name="fabricante",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pecas",
                to="inventory.fabricante",
                verbose_name="Fabricante",
            ),
        ),
    ]
