# Generated by Django 5.2.10 on 2026-02-02 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Motor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Ex: Gerador 01 - Principal", max_length=100
                    ),
                ),
                ("marca", models.CharField(default="Jenbacher", max_length=100)),
                ("modelo", models.CharField(help_text="Ex: J620", max_length=100)),
                ("numero_serie", models.CharField(max_length=100)),
                (
                    "localizacao",
                    models.CharField(
                        help_text="Ex: Sala de Máquinas A", max_length=100
                    ),
                ),
                ("potencia_nominal", models.CharField(blank=True, max_length=50)),
                (
                    "qtd_cilindros",
                    models.IntegerField(
                        default=16,
                        help_text="Define quantos kits de cilindro serão criados",
                    ),
                ),
                (
                    "qtd_baterias",
                    models.IntegerField(default=2, verbose_name="Qtd. Baterias"),
                ),
                (
                    "qtd_motores_partida",
                    models.IntegerField(
                        default=1, verbose_name="Qtd. Motores de Partida"
                    ),
                ),
                (
                    "qtd_turbos",
                    models.IntegerField(default=2, verbose_name="Qtd. Turbinas"),
                ),
                (
                    "qtd_filtros_oleo",
                    models.IntegerField(default=1, verbose_name="Qtd. Filtros de Óleo"),
                ),
                (
                    "horas_totais",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_arranques",
                    models.IntegerField(
                        default=0, help_text="Número total de partidas dadas"
                    ),
                ),
                ("em_operacao", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PosicaoComponente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(help_text="Ex: Cilindro 1 - Vela", max_length=200),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True,
                        help_text="Serial da peça física (se houver)",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("data_instalacao", models.DateField(blank=True, null=True)),
                (
                    "hora_motor_instalacao",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Quantas horas o motor tinha quando essa peça foi colocada?",
                        max_digits=10,
                    ),
                ),
                (
                    "arranques_motor_instalacao",
                    models.IntegerField(
                        default=0,
                        help_text="Quantos arranques o motor tinha quando essa peça foi colocada?",
                    ),
                ),
                ("ultima_medicao_vibracao", models.DateField(blank=True, null=True)),
                ("ultimo_engraxamento", models.DateField(blank=True, null=True)),
                (
                    "motor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="componentes",
                        to="assets.motor",
                    ),
                ),
                (
                    "peca_instalada",
                    models.ForeignKey(
                        blank=True,
                        help_text="Qual modelo de peça está aqui?",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.catalogopeca",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "verbose_name": "Posição/Componente",
                "verbose_name_plural": "Posições/Componentes",
                "ordering": ["nome"],
            },
        ),
    ]
