# Generated by Django 5.2.10 on 2026-02-03 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="motor",
            name="marca",
        ),
        migrations.CreateModel(
            name="MarcaMotor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Ex: Jenbacher, Caterpillar, MWM",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "verbose_name": "Marca de Motor",
                "verbose_name_plural": "Marcas de Motor",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="ModeloMotor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(help_text="Ex: J620, J420, G3516", max_length=100),
                ),
                (
                    "marca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modelos",
                        to="assets.marcamotor",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "verbose_name": "Modelo de Motor",
                "verbose_name_plural": "Modelos de Motor",
                "ordering": ["marca", "nome"],
                "unique_together": {("marca", "nome")},
            },
        ),
        migrations.AlterField(
            model_name="motor",
            name="modelo",
            field=models.ForeignKey(
                help_text="Selecione o modelo (A marca será identificada automaticamente)",
                on_delete=django.db.models.deletion.PROTECT,
                to="assets.modelomotor",
                verbose_name="Modelo do Motor",
            ),
        ),
    ]
