# Generated by Django 5.2.10 on 2026-02-03 04:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0002_remove_motor_marca_marcamotor_modelomotor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="motor",
            name="horas_totais",
            field=models.IntegerField(default=0, help_text="Horas Totais (Inteiro)"),
        ),
        migrations.AlterField(
            model_name="posicaocomponente",
            name="hora_motor_instalacao",
            field=models.IntegerField(
                default=0,
                help_text="Quantas horas o motor tinha quando essa peça foi colocada?",
            ),
        ),
    ]
