# Generated by Django 5.2.10 on 2026-02-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0003_alter_motor_horas_totais_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="motor",
            name="blowby",
            field=models.CharField(
                blank=True,
                default="Padrão",
                help_text="Tipo de respiro ou filtro de blowby",
                max_length=100,
                verbose_name="Sistema Blowby",
            ),
        ),
        migrations.AddField(
            model_name="motor",
            name="modelo_filtro_ar",
            field=models.CharField(
                blank=True,
                help_text="Ex: Cônico, Inbox, ou Código da Peça",
                max_length=100,
                null=True,
                verbose_name="Modelo do Filtro de Ar",
            ),
        ),
        migrations.AddField(
            model_name="motor",
            name="qtd_bobinas",
            field=models.IntegerField(
                blank=True,
                help_text="Se vazio, assume a quantidade de cilindros",
                null=True,
                verbose_name="Qtd. Bobinas",
            ),
        ),
        migrations.AddField(
            model_name="motor",
            name="qtd_cabos_vela",
            field=models.IntegerField(
                blank=True,
                help_text="Se vazio, assume a quantidade de cilindros",
                null=True,
                verbose_name="Qtd. Cabos de Vela",
            ),
        ),
        migrations.AddField(
            model_name="motor",
            name="qtd_filtros_ar",
            field=models.IntegerField(default=1, verbose_name="Qtd. Filtros de Ar"),
        ),
        migrations.AddField(
            model_name="motor",
            name="qtd_filtros_gas",
            field=models.IntegerField(
                default=1, verbose_name="Qtd. Filtros de Gás/Combustível"
            ),
        ),
    ]
