# Generated by Django 5.2.10 on 2026-02-03 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0004_motor_blowby_motor_modelo_filtro_ar_and_more"),
        ("inventory", "0003_alter_estoqueitem_minimo_seguranca_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Periferico",
            fields=[],
            options={
                "verbose_name": "Periférico",
                "verbose_name_plural": "Periféricos (Filtros, Turbos, Etc)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("assets.posicaocomponente",),
        ),
        migrations.AddField(
            model_name="motor",
            name="qtd_alternadores",
            field=models.IntegerField(default=1, verbose_name="Qtd. Alternadores"),
        ),
        migrations.AddField(
            model_name="motor",
            name="qtd_intercoolers",
            field=models.IntegerField(default=1, verbose_name="Qtd. Intercoolers"),
        ),
        migrations.AddField(
            model_name="motor",
            name="qtd_trocadores_oleo",
            field=models.IntegerField(
                default=1, verbose_name="Qtd. Trocadores de Óleo"
            ),
        ),
        migrations.AlterField(
            model_name="modelomotor",
            name="nome",
            field=models.CharField(help_text="Ex: J620, J420", max_length=100),
        ),
        migrations.AlterField(
            model_name="motor",
            name="blowby",
            field=models.CharField(
                blank=True,
                default="Padrão",
                max_length=100,
                verbose_name="Sistema Blowby",
            ),
        ),
        migrations.AlterField(
            model_name="motor",
            name="modelo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="assets.modelomotor",
                verbose_name="Modelo",
            ),
        ),
        migrations.AlterField(
            model_name="motor",
            name="modelo_filtro_ar",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Modelo Filtro Ar"
            ),
        ),
        migrations.AlterField(
            model_name="motor",
            name="qtd_bobinas",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Qtd. Bobinas"
            ),
        ),
        migrations.AlterField(
            model_name="motor",
            name="qtd_cabos_vela",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Qtd. Cabos de Vela"
            ),
        ),
        migrations.AlterField(
            model_name="motor",
            name="qtd_filtros_gas",
            field=models.IntegerField(default=1, verbose_name="Qtd. Filtros de Gás"),
        ),
        migrations.AlterField(
            model_name="motor",
            name="total_arranques",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="posicaocomponente",
            name="arranques_motor_instalacao",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="posicaocomponente",
            name="hora_motor_instalacao",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="posicaocomponente",
            name="peca_instalada",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.catalogopeca",
                verbose_name="Peça / Modelo",
            ),
        ),
        migrations.AlterField(
            model_name="posicaocomponente",
            name="serial_number",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Nº de Série"
            ),
        ),
    ]
