# Generated by Django 5.2.10 on 2026-02-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0005_periferico_motor_qtd_alternadores_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="motor",
            name="blowby",
        ),
        migrations.AddField(
            model_name="motor",
            name="qtd_blowby",
            field=models.IntegerField(default=1, verbose_name="Qtd. Blowby"),
        ),
    ]
