# Generated by Django 5.2.10 on 2026-02-03 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0006_remove_motor_blowby_motor_qtd_blowby"),
        ("inventory", "0003_alter_estoqueitem_minimo_seguranca_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SistemaArrefecimento",
            fields=[],
            options={
                "verbose_name": "Item de Arrefecimento",
                "verbose_name_plural": "3. Gestão de Arrefecimento",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("assets.posicaocomponente",),
        ),
        migrations.CreateModel(
            name="SistemaOleo",
            fields=[],
            options={
                "verbose_name": "Item de Óleo",
                "verbose_name_plural": "2. Gestão de Óleo",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("assets.posicaocomponente",),
        ),
        migrations.AlterModelOptions(
            name="modelomotor",
            options={
                "verbose_name": "Modelo de Motor",
                "verbose_name_plural": "Modelos de Motor",
            },
        ),
        migrations.AlterModelOptions(
            name="periferico",
            options={
                "verbose_name": "Periférico Geral",
                "verbose_name_plural": "1. Periféricos Gerais",
            },
        ),
        migrations.AddField(
            model_name="posicaocomponente",
            name="data_ultima_coleta",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data Última Coleta"
            ),
        ),
        migrations.AddField(
            model_name="posicaocomponente",
            name="resultado_ultima_coleta",
            field=models.CharField(
                blank=True,
                choices=[
                    ("VERDE", "Normal (Verde)"),
                    ("AMARELO", "Atenção (Amarelo)"),
                    ("VERMELHO", "Crítico (Vermelho)"),
                ],
                max_length=20,
                null=True,
                verbose_name="Resultado Análise",
            ),
        ),
        migrations.AlterField(
            model_name="marcamotor",
            name="nome",
            field=models.CharField(
                help_text="Ex: Jenbacher", max_length=100, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="modelomotor",
            name="nome",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="motor",
            name="horas_totais",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="motor",
            name="localizacao",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="motor",
            name="nome",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="motor",
            name="qtd_cilindros",
            field=models.IntegerField(default=16),
        ),
        migrations.AlterField(
            model_name="posicaocomponente",
            name="data_instalacao",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data Última Troca"
            ),
        ),
        migrations.AlterField(
            model_name="posicaocomponente",
            name="nome",
            field=models.CharField(help_text="Ex: Óleo do Motor", max_length=200),
        ),
        migrations.AlterField(
            model_name="posicaocomponente",
            name="peca_instalada",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.catalogopeca",
            ),
        ),
        migrations.AlterField(
            model_name="posicaocomponente",
            name="serial_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
