# Generated by Django 5.2.10 on 2026-02-03 23:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0007_sistemaarrefecimento_sistemaoleo_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sistemaarrefecimento",
            options={
                "verbose_name": "Item de Arrefecimento",
                "verbose_name_plural": "3. Arrefecimento",
            },
        ),
        migrations.AlterModelOptions(
            name="sistemaoleo",
            options={"verbose_name": "Item de Óleo", "verbose_name_plural": "Óleo"},
        ),
        migrations.AddField(
            model_name="posicaocomponente",
            name="data_ultima_analise",
            field=models.DateField(blank=True, null=True, verbose_name="Data Análise"),
        ),
        migrations.AddField(
            model_name="posicaocomponente",
            name="horas_na_coleta",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Horas na Coleta"
            ),
        ),
        migrations.AlterField(
            model_name="marcamotor",
            name="nome",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="posicaocomponente",
            name="data_ultima_coleta",
            field=models.DateField(blank=True, null=True, verbose_name="Data Coleta"),
        ),
        migrations.AlterField(
            model_name="posicaocomponente",
            name="hora_motor_instalacao",
            field=models.IntegerField(
                default=0, help_text="Horímetro do motor no momento da troca"
            ),
        ),
        migrations.AlterField(
            model_name="posicaocomponente",
            name="resultado_ultima_coleta",
            field=models.CharField(
                blank=True,
                choices=[
                    ("VERDE", "Normal (Verde)"),
                    ("AMARELO", "Atenção (Amarelo)"),
                    ("VERMELHO", "Crítico (Vermelho)"),
                ],
                max_length=20,
                null=True,
                verbose_name="Situação",
            ),
        ),
        migrations.AlterField(
            model_name="posicaocomponente",
            name="serial_number",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Nº Série"
            ),
        ),
    ]
