# Generated by Django 5.2.10 on 2026-02-03 23:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0008_alter_sistemaarrefecimento_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posicaocomponente",
            name="hora_motor_instalacao",
            field=models.IntegerField(default=0),
        ),
    ]
