# Generated by Django 5.2.10 on 2026-02-03 23:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0009_alter_posicaocomponente_hora_motor_instalacao"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Periferico",
        ),
        migrations.DeleteModel(
            name="SistemaArrefecimento",
        ),
        migrations.AlterField(
            model_name="motor",
            name="modelo_filtro_ar",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="motor",
            name="qtd_alternadores",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="motor",
            name="qtd_baterias",
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name="motor",
            name="qtd_blowby",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="motor",
            name="qtd_bobinas",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="motor",
            name="qtd_cabos_vela",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="motor",
            name="qtd_filtros_ar",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="motor",
            name="qtd_filtros_gas",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="motor",
            name="qtd_intercoolers",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="motor",
            name="qtd_motores_partida",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="motor",
            name="qtd_turbos",
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name="posicaocomponente",
            name="data_ultima_analise",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="posicaocomponente",
            name="data_ultima_coleta",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="posicaocomponente",
            name="hora_motor_instalacao",
            field=models.IntegerField(
                default=0, help_text="Horímetro do motor na troca"
            ),
        ),
        migrations.AlterField(
            model_name="posicaocomponente",
            name="horas_na_coleta",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="posicaocomponente",
            name="nome",
            field=models.CharField(help_text="Ex: Óleo", max_length=200),
        ),
        migrations.AlterField(
            model_name="posicaocomponente",
            name="resultado_ultima_coleta",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="posicaocomponente",
            name="serial_number",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Nº de Série"
            ),
        ),
    ]
