# Generated by Django 5.2.10 on 2026-02-03 23:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0010_delete_periferico_delete_sistemaarrefecimento_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Periferico",
            fields=[],
            options={
                "verbose_name": "Periférico",
                "verbose_name_plural": "Periféricos",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("assets.posicaocomponente",),
        ),
        migrations.AddField(
            model_name="motor",
            name="qtd_bypass",
            field=models.IntegerField(default=1, verbose_name="Qtd. Válvulas Bypass"),
        ),
        migrations.AddField(
            model_name="motor",
            name="qtd_compensadores",
            field=models.IntegerField(
                default=1, verbose_name="Qtd. Compensadores Escape"
            ),
        ),
        migrations.AddField(
            model_name="motor",
            name="qtd_dampers",
            field=models.IntegerField(default=1, verbose_name="Qtd. Dampers"),
        ),
        migrations.AddField(
            model_name="motor",
            name="qtd_pre_filtros_ar",
            field=models.IntegerField(default=1, verbose_name="Qtd. Pré-Filtros de Ar"),
        ),
        migrations.AddField(
            model_name="motor",
            name="qtd_resistencias",
            field=models.IntegerField(
                default=1, verbose_name="Qtd. Resistências Aquec."
            ),
        ),
        migrations.AlterField(
            model_name="motor",
            name="qtd_alternadores",
            field=models.IntegerField(default=1, verbose_name="Qtd. Alternadores"),
        ),
        migrations.AlterField(
            model_name="motor",
            name="qtd_blowby",
            field=models.IntegerField(default=1, verbose_name="Qtd. Blowby"),
        ),
        migrations.AlterField(
            model_name="motor",
            name="qtd_filtros_ar",
            field=models.IntegerField(default=1, verbose_name="Qtd. Filtros de Ar"),
        ),
        migrations.AlterField(
            model_name="motor",
            name="qtd_filtros_gas",
            field=models.IntegerField(default=1, verbose_name="Qtd. Filtros de Gás"),
        ),
        migrations.AlterField(
            model_name="motor",
            name="qtd_intercoolers",
            field=models.IntegerField(default=1, verbose_name="Qtd. Intercoolers"),
        ),
        migrations.AlterField(
            model_name="motor",
            name="qtd_motores_partida",
            field=models.IntegerField(
                default=1, verbose_name="Qtd. Motores de Arranque"
            ),
        ),
        migrations.AlterField(
            model_name="motor",
            name="qtd_turbos",
            field=models.IntegerField(default=2, verbose_name="Qtd. Turbos"),
        ),
        migrations.AlterField(
            model_name="posicaocomponente",
            name="hora_motor_instalacao",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="posicaocomponente",
            name="nome",
            field=models.CharField(max_length=200),
        ),
    ]
