# Generated by Django 5.2.10 on 2026-02-04 00:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0011_periferico_motor_qtd_bypass_motor_qtd_compensadores_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="posicaocomponente",
            name="motor",
        ),
        migrations.RemoveField(
            model_name="posicaocomponente",
            name="peca_instalada",
        ),
        migrations.RemoveField(
            model_name="posicaocomponente",
            name="tenant",
        ),
        migrations.DeleteModel(
            name="Periferico",
        ),
        migrations.DeleteModel(
            name="SistemaOleo",
        ),
        migrations.AlterModelOptions(
            name="motor",
            options={"verbose_name": "Motor", "verbose_name_plural": "Motores"},
        ),
    ]
