# Generated by Django 5.2.10 on 2026-02-04 01:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0012_remove_posicaocomponente_motor_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PosicaoComponente",
        ),
    ]
