# Generated by Django 5.2.10 on 2026-02-04 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0013_delete_posicaocomponente"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="marcamotor",
            options={"ordering": ["nome"], "verbose_name": "Marca"},
        ),
        migrations.AlterModelOptions(
            name="modelomotor",
            options={"verbose_name": "Modelo"},
        ),
        migrations.RemoveField(
            model_name="motor",
            name="potencia_nominal",
        ),
        migrations.RemoveField(
            model_name="motor",
            name="qtd_blowby",
        ),
        migrations.AddField(
            model_name="motor",
            name="qtd_bielas",
            field=models.IntegerField(default=0, verbose_name="Qtd. Bielas"),
        ),
        migrations.AddField(
            model_name="motor",
            name="qtd_bronzinas",
            field=models.IntegerField(default=0, verbose_name="Qtd. Bronzinas"),
        ),
        migrations.AddField(
            model_name="motor",
            name="qtd_camisas",
            field=models.IntegerField(default=0, verbose_name="Qtd. Camisas"),
        ),
        migrations.AddField(
            model_name="motor",
            name="qtd_pistoes",
            field=models.IntegerField(default=0, verbose_name="Qtd. Pistões"),
        ),
        migrations.AddField(
            model_name="motor",
            name="qtd_velas",
            field=models.IntegerField(default=0, verbose_name="Qtd. Velas"),
        ),
        migrations.AlterField(
            model_name="modelomotor",
            name="marca",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="assets.marcamotor"
            ),
        ),
        migrations.AlterField(
            model_name="motor",
            name="modelo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="assets.modelomotor"
            ),
        ),
        migrations.AlterField(
            model_name="motor",
            name="qtd_baterias",
            field=models.IntegerField(default=2, verbose_name="Qtd. Baterias"),
        ),
        migrations.AlterField(
            model_name="motor",
            name="qtd_bobinas",
            field=models.IntegerField(default=0, verbose_name="Qtd. Bobinas"),
        ),
        migrations.AlterField(
            model_name="motor",
            name="qtd_cabos_vela",
            field=models.IntegerField(default=0, verbose_name="Qtd. Cabos de Vela"),
        ),
        migrations.AlterField(
            model_name="motor",
            name="qtd_cilindros",
            field=models.IntegerField(
                default=12, verbose_name="Qtd. Cilindros (Geral)"
            ),
        ),
        migrations.AlterField(
            model_name="motor",
            name="qtd_filtros_ar",
            field=models.IntegerField(default=2, verbose_name="Qtd. Filtros de Ar"),
        ),
        migrations.AlterField(
            model_name="motor",
            name="qtd_filtros_gas",
            field=models.IntegerField(default=0, verbose_name="Qtd. Filtros de Gás"),
        ),
        migrations.AlterField(
            model_name="motor",
            name="qtd_intercoolers",
            field=models.IntegerField(default=2, verbose_name="Qtd. Intercoolers"),
        ),
        migrations.AlterField(
            model_name="motor",
            name="qtd_pre_filtros_ar",
            field=models.IntegerField(default=0, verbose_name="Qtd. Pré-Filtros de Ar"),
        ),
    ]
