# Generated by Django 5.2.10 on 2026-02-23 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0014_alter_marcamotor_options_alter_modelomotor_options_and_more"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("fabricante", models.CharField(blank=True, max_length=100, null=True)),
                ("modelo", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "numero_serie",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("localizacao", models.CharField(max_length=100)),
                (
                    "horas_totais",
                    models.IntegerField(default=0, verbose_name="Horímetro Atual"),
                ),
                ("em_operacao", models.BooleanField(default=True)),
                (
                    "motor_associado",
                    models.ForeignKey(
                        blank=True,
                        help_text="Se este equipamento atende a um motor específico (ex: Blower da Sala 1)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="perifericos_externos",
                        to="assets.motor",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipamento / Periférico",
                "verbose_name_plural": "Equipamentos e Periféricos",
            },
        ),
    ]
