# Generated by Django 5.2.10 on 2026-02-23 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0015_equipamento"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="equipamento",
            options={
                "ordering": ["nome"],
                "verbose_name": "Equipamento / Periférico",
                "verbose_name_plural": "Equipamentos e Periféricos",
            },
        ),
        migrations.AlterField(
            model_name="equipamento",
            name="em_operacao",
            field=models.BooleanField(default=True, verbose_name="Em Operação?"),
        ),
        migrations.AlterField(
            model_name="equipamento",
            name="localizacao",
            field=models.CharField(max_length=100, verbose_name="Localização"),
        ),
        migrations.AlterField(
            model_name="equipamento",
            name="motor_associado",
            field=models.ForeignKey(
                blank=True,
                help_text="Se este equipamento atende a um motor específico (ex: Blower da Sala 1)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="perifericos_externos",
                to="assets.motor",
                verbose_name="Motor Associado (Opcional)",
            ),
        ),
    ]
