# Generated by Django 5.2.10 on 2026-02-02 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("assets", "0001_initial"),
        ("core", "0001_initial"),
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroManutencao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_ocorrencia", models.DateTimeField()),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "tipo_atividade",
                    models.CharField(
                        choices=[
                            ("TROCA", "Substituição de Peça"),
                            ("INSPECAO", "Inspeção / Verificação"),
                            ("LUBRIFICACAO", "Lubrificação / Engraxamento"),
                            ("AJUSTE", "Ajuste / Regulagem"),
                            ("FALHA", "Registro de Falha (Quebra)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "horimetro_na_execucao",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Horas do motor no momento da ação",
                        max_digits=10,
                    ),
                ),
                (
                    "novo_serial_number",
                    models.CharField(
                        blank=True,
                        help_text="Serial da nova peça (se aplicável)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "observacao",
                    models.TextField(blank=True, verbose_name="Relato do Técnico"),
                ),
                (
                    "item_estoque_utilizado",
                    models.ForeignKey(
                        blank=True,
                        help_text="Se houve troca, de qual estoque saiu a peça nova?",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.estoqueitem",
                    ),
                ),
                (
                    "motor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="assets.motor"
                    ),
                ),
                (
                    "posicao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="assets.posicaocomponente",
                        verbose_name="Componente Afetado",
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Manutenção",
                "verbose_name_plural": "Livro de Ocorrências",
                "ordering": ["-data_ocorrencia"],
            },
        ),
    ]
