# Generated by Django 5.2.10 on 2026-02-03 04:53

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0003_alter_motor_horas_totais_and_more"),
        ("inventory", "0003_alter_estoqueitem_minimo_seguranca_and_more"),
        ("maintenance", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="registromanutencao",
            old_name="criado_em",
            new_name="created_at",
        ),
        migrations.AlterField(
            model_name="registromanutencao",
            name="data_ocorrencia",
            field=models.DateField(default=django.db.models.functions.datetime.Now),
        ),
        migrations.AlterField(
            model_name="registromanutencao",
            name="horimetro_na_execucao",
            field=models.IntegerField(
                help_text="Quantas horas totais o motor tinha nesta data?",
                verbose_name="Horímetro no momento",
            ),
        ),
        migrations.AlterField(
            model_name="registromanutencao",
            name="item_estoque_utilizado",
            field=models.ForeignKey(
                blank=True,
                help_text="Selecione a peça que foi consumida",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.estoqueitem",
                verbose_name="Peça do Estoque",
            ),
        ),
        migrations.AlterField(
            model_name="registromanutencao",
            name="motor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="assets.motor"
            ),
        ),
        migrations.AlterField(
            model_name="registromanutencao",
            name="novo_serial_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="registromanutencao",
            name="observacao",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="registromanutencao",
            name="posicao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="assets.posicaocomponente",
                verbose_name="Posição / Componente",
            ),
        ),
        migrations.AlterField(
            model_name="registromanutencao",
            name="tipo_atividade",
            field=models.CharField(
                choices=[
                    ("PREVENTIVA", "Manutenção Preventiva"),
                    ("CORRETIVA", "Manutenção Corretiva"),
                    ("LUBRIFICACAO", "Lubrificação / Engraxamento"),
                    ("TROCA", "Substituição de Peça"),
                    ("INSPECAO", "Inspeção de Rotina"),
                ],
                max_length=20,
            ),
        ),
    ]
