# Generated by Django 5.2.10 on 2026-02-04 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0012_remove_posicaocomponente_motor_and_more"),
        ("components", "0001_initial"),
        ("maintenance", "0002_rename_criado_em_registromanutencao_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="registromanutencao",
            options={
                "ordering": ["-data_ocorrencia"],
                "verbose_name": "Registro de Manutenção",
                "verbose_name_plural": "Registros de Manutenção",
            },
        ),
        migrations.RemoveField(
            model_name="registromanutencao",
            name="item_estoque_utilizado",
        ),
        migrations.AlterField(
            model_name="registromanutencao",
            name="data_ocorrencia",
            field=models.DateField(verbose_name="Data da Ocorrência"),
        ),
        migrations.AlterField(
            model_name="registromanutencao",
            name="horimetro_na_execucao",
            field=models.IntegerField(default=0, verbose_name="Horímetro na Execução"),
        ),
        migrations.AlterField(
            model_name="registromanutencao",
            name="motor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manutencoes",
                to="assets.motor",
            ),
        ),
        migrations.AlterField(
            model_name="registromanutencao",
            name="novo_serial_number",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Novo Nº de Série (Se houve troca)",
            ),
        ),
        migrations.AlterField(
            model_name="registromanutencao",
            name="observacao",
            field=models.TextField(blank=True, null=True, verbose_name="Observações"),
        ),
        migrations.AlterField(
            model_name="registromanutencao",
            name="posicao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historico_manutencao",
                to="components.posicaocomponente",
            ),
        ),
        migrations.AlterField(
            model_name="registromanutencao",
            name="responsavel",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Responsável"
            ),
        ),
        migrations.AlterField(
            model_name="registromanutencao",
            name="tipo_atividade",
            field=models.CharField(
                choices=[("CORRETIVA", "Corretiva"), ("PREVENTIVA", "Preventiva")],
                default="PREVENTIVA",
                max_length=50,
            ),
        ),
    ]
