# Generated by Django 5.2.10 on 2026-02-04 01:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("maintenance", "0003_alter_registromanutencao_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registromanutencao",
            name="horimetro_na_execucao",
        ),
        migrations.RemoveField(
            model_name="registromanutencao",
            name="novo_serial_number",
        ),
        migrations.RemoveField(
            model_name="registromanutencao",
            name="observacao",
        ),
        migrations.RemoveField(
            model_name="registromanutencao",
            name="responsavel",
        ),
    ]
