# Generated by Django 5.2.10 on 2026-02-04 02:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("components", "0001_initial"),
        (
            "maintenance",
            "0004_remove_registromanutencao_horimetro_na_execucao_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ComponenteGeral",
            fields=[],
            options={
                "verbose_name": "Geral",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("components.posicaocomponente",),
        ),
        migrations.CreateModel(
            name="Periferico",
            fields=[],
            options={
                "verbose_name": "Periférico",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("components.posicaocomponente",),
        ),
        migrations.CreateModel(
            name="SistemaOleo",
            fields=[],
            options={
                "verbose_name": "Óleo",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("components.posicaocomponente",),
        ),
        migrations.RemoveField(
            model_name="registromanutencao",
            name="created_at",
        ),
    ]
