# Generated by Django 5.2.10 on 2026-02-04 03:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "components",
            "0004_menucabecotes_menucilindros_alter_menuoutros_options_and_more",
        ),
        ("maintenance", "0005_componentegeral_periferico_sistemaoleo_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ComponenteGeral",
        ),
        migrations.DeleteModel(
            name="Periferico",
        ),
        migrations.DeleteModel(
            name="SistemaOleo",
        ),
        migrations.AlterModelOptions(
            name="registromanutencao",
            options={
                "ordering": ["-data_ocorrencia"],
                "verbose_name": "Livro de Ocorrência",
                "verbose_name_plural": "Livro de Ocorrências",
            },
        ),
        migrations.AddField(
            model_name="registromanutencao",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="registromanutencao",
            name="horimetro_na_execucao",
            field=models.IntegerField(default=0, verbose_name="Horímetro na Execução"),
        ),
        migrations.AddField(
            model_name="registromanutencao",
            name="novo_serial_number",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Novo Nº de Série (Se houve troca)",
            ),
        ),
        migrations.AddField(
            model_name="registromanutencao",
            name="observacao",
            field=models.TextField(
                blank=True, null=True, verbose_name="Descrição do Serviço / Observações"
            ),
        ),
        migrations.AddField(
            model_name="registromanutencao",
            name="responsavel",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Responsável Técnico",
            ),
        ),
        migrations.AlterField(
            model_name="registromanutencao",
            name="posicao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historico_manutencao",
                to="components.posicaocomponente",
                verbose_name="Componente Afetado",
            ),
        ),
    ]
