# Generated by Django 5.2.10 on 2026-02-04 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "components",
            "0004_menucabecotes_menucilindros_alter_menuoutros_options_and_more",
        ),
        ("inventory", "0004_movimentoestoque"),
        ("maintenance", "0006_delete_componentegeral_delete_periferico_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="registromanutencao",
            options={
                "ordering": ["-data_ocorrencia"],
                "verbose_name": "Registro de Ocorrência",
                "verbose_name_plural": "Livro de Ocorrências",
            },
        ),
        migrations.AddField(
            model_name="registromanutencao",
            name="arranques_na_execucao",
            field=models.IntegerField(
                blank=True,
                help_text="Deixe em branco se não quiser alterar.",
                null=True,
                verbose_name="Nº de Arranques (Opcional)",
            ),
        ),
        migrations.AddField(
            model_name="registromanutencao",
            name="item_estoque",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.estoqueitem",
                verbose_name="Item de Estoque (Para Baixa)",
            ),
        ),
        migrations.AddField(
            model_name="registromanutencao",
            name="quantidade_utilizada",
            field=models.IntegerField(default=0, verbose_name="Quantidade a Baixar"),
        ),
        migrations.AlterField(
            model_name="registromanutencao",
            name="horimetro_na_execucao",
            field=models.IntegerField(
                help_text="Atualizará o horímetro de instalação da peça se for uma troca.",
                verbose_name="Horas de Operação (Atual)",
            ),
        ),
        migrations.AlterField(
            model_name="registromanutencao",
            name="novo_serial_number",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Novo Serial (Se houver)",
            ),
        ),
        migrations.AlterField(
            model_name="registromanutencao",
            name="observacao",
            field=models.TextField(
                blank=True, null=True, verbose_name="Detalhes / Observações"
            ),
        ),
        migrations.AlterField(
            model_name="registromanutencao",
            name="posicao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historico_manutencao",
                to="components.posicaocomponente",
                verbose_name="Equipamento (Componente)",
            ),
        ),
        migrations.AlterField(
            model_name="registromanutencao",
            name="responsavel",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Responsável"
            ),
        ),
        migrations.AlterField(
            model_name="registromanutencao",
            name="tipo_atividade",
            field=models.CharField(
                choices=[
                    ("SUBSTITUICAO", "Substituição (Troca de Peça)"),
                    ("INSTALACAO", "Instalação (Nova Peça)"),
                    ("REGULAGEM", "Regulagem"),
                    ("LUBRIFICACAO", "Lubrificação"),
                    ("CALIBRACAO", "Calibração"),
                    ("INSPECAO", "Inspeção / Rotina"),
                    ("CORRETIVA", "Reparo Corretivo"),
                ],
                default="INSPECAO",
                max_length=50,
                verbose_name="Tipo de Serviço",
            ),
        ),
    ]
