# Generated by Django 5.2.10 on 2026-02-04 05:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "components",
            "0004_menucabecotes_menucilindros_alter_menuoutros_options_and_more",
        ),
        ("maintenance", "0007_alter_registromanutencao_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registromanutencao",
            name="posicao",
        ),
        migrations.AddField(
            model_name="registromanutencao",
            name="componentes",
            field=models.ManyToManyField(
                related_name="historico_manutencao",
                to="components.posicaocomponente",
                verbose_name="Equipamentos (Componentes)",
            ),
        ),
        migrations.AlterField(
            model_name="registromanutencao",
            name="horimetro_na_execucao",
            field=models.IntegerField(
                help_text="Atualizará o horímetro de todos os componentes selecionados.",
                verbose_name="Horas de Operação (Atual)",
            ),
        ),
    ]
