# Generated by Django 5.2.10 on 2026-02-04 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("components", "0005_alter_posicaocomponente_options_and_more"),
        ("maintenance", "0008_remove_registromanutencao_posicao_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registromanutencao",
            name="componentes",
        ),
        migrations.AddField(
            model_name="registromanutencao",
            name="posicao",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historico_manutencao",
                to="components.posicaocomponente",
                verbose_name="Componente Afetado",
            ),
            preserve_default=False,
        ),
    ]
