# Generated by Django 5.2.10 on 2026-02-06 03:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maintenance", "0009_remove_registromanutencao_componentes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registromanutencao",
            name="tipo_atividade",
            field=models.CharField(
                choices=[
                    ("SUBSTITUICAO", "Substituição (Troca de Peça)"),
                    ("INSTALACAO", "Instalação (Nova Peça)"),
                    ("REGULAGEM", "Regulagem"),
                    ("LUBRIFICACAO", "Lubrificação"),
                    ("CALIBRACAO", "Calibração"),
                    ("INSPECAO", "Inspeção / Rotina"),
                    ("CORRETIVA", "Reparo Corretivo"),
                    ("LIMPEZA", "Limpeza"),
                ],
                default="INSPECAO",
                max_length=50,
                verbose_name="Tipo de Serviço",
            ),
        ),
    ]
