# Generated by Django 5.2.10 on 2026-02-23 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0016_alter_equipamento_options_and_more"),
        ("maintenance", "0010_alter_registromanutencao_tipo_atividade"),
    ]

    operations = [
        migrations.AddField(
            model_name="registromanutencao",
            name="equipamento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manutencoes",
                to="assets.equipamento",
            ),
        ),
        migrations.AlterField(
            model_name="registromanutencao",
            name="motor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manutencoes",
                to="assets.motor",
            ),
        ),
    ]
